<div id="main" class="terms">
	<p class="submenu"><a id="sm1" href="<?php echo site_url('mobile_terms_conditions'); ?>">Mobile Terms &amp; Conditions</a>  <a id="sm2" class="active" style="left:-10px;" href="<?php echo site_url('business_terms_conditions'); ?>">Business Terms &amp; Conditions</a>  <a id="sm3" style="left:-20px;" href="<?php echo site_url('privacy_policy'); ?>">Privacy Policy</a>  <a id="sm4" style="left:-30px;" href="<?php echo site_url('sweepstakes_rules'); ?>">Contest Rules</a></p>
	
	<h1>Business Terms and Conditions</h1>

	<h3>I. THE TELL THE BOSS SERVICE</h3>
	<ol class="primary">
		<li>Services Defined. TELL THE BOSS, INC. ("TELL THE BOSS") provides business owners and organizations our trademarked service to collect feedback from their customers, and provides tools to help them receive the data quickly and efficiently in various proprietary formats. Our service may also provide a variety of tools and resources to create and manage surveys and feedback offerings. For purposes of this Agreement the term "Services" shall mean all the above mentioned products and related offerings. </li>
		<li>During the term of this Agreement and subject to the terms and conditions of use set forth herein and any guidelines, rules or operating policies that TELL THE BOSS may establish and post from time to time on www.telltheboss.com (the "Site"), including, without limitation TELL THE BOSS's Anti-SPAM Policy, and Privacy Policy (collectively, the "Policies") which are incorporated herein by reference, TELL THE BOSS agrees to use commercially reasonable efforts to provide you with the Services. From time to time, TELL THE BOSS may modify the terms and conditions of this Agreement and/or the Policies. All such changes shall become effective upon posting of the revised Agreement and/or Policies, as the case may be, on the Site, and Your use of the Services thereafter shall be subject thereto. You agree that your purchase of the Services is neither contingent upon the delivery of any future functionality or features, nor is it dependent upon any oral or written comments made by TELL THE BOSS with respect to future functionality or features. </li>
		<li>Service Changes. Except as otherwise set forth in this Agreement, you may change your product selection at any time by notifying us. A fee may apply to such changes.</li>
		<li>Changes in Services Offered. TELL THE BOSS reserves the right to change the Services that we offer, and our prices or fees related to such Services at any time. If the change affects you, we will provide you notice of the change and its effective date. The notice may be provided on your billing statement or by other communication method. In the event of a change in the contents of any Services, you understand and agree that we have no obligation to replace or supplement the products or other Services previously offered that have been discontinued, rearranged or otherwise changed. You further understand and agree you will not be entitled to any refund because of a change in the other Services previously offered.</li>
		<li>Multi-Month Subscriptions. For multi-month subscriptions, you may downgrade the Services only at the time of subscription renewal. You may not downgrade the Services during the term of the multi-month subscription.</li>
	</ol>
	
	<h3>II. BILLING POLICIES AND PAYMENTS FOR SERVICES</h3>
	<ol class="primary">
		<li>You agree to pay all amounts billed for Services and to pay all taxes, fees and other charges, if any, which are now or may in the future be assessed on the Services you receive from us. Unless you prepay for a multi-month subscription to Services, we will bill you each billing cycle(monthly, quarterly, semi-annual, annual or bi-annual based on your subscription period), in advance, for Services ordered by you or anyone who uses the TELL THE BOSS Services, whether with or without your permission, until you cancel the Services. The bills you receive will show the total amount due, the payment due date, payments, credits, purchases and any other charges to your account.</li>
		<li>Payment for Services will be made by a valid credit card or check. If the recurring payment option is selected or if you have previously provided your credit card for payment, you hereby authorize TELL THE BOSS to charge your credit card for such amounts on a regular monthly or quarterly or semi-annual or annual or bi-annual basis beginning at the beginning of your paid subscription and continuing until such time as your account is terminated. If TELL THE BOSS is for any reason unable to effect automatic payment via your credit card, TELL THE BOSS will attempt to notify you via email or phone and your TELL THE BOSS account may be disabled until payment is received. Amounts paid for the Services are not refundable.</li>
		<li>You agree to pay us in full by the payment due date for the Services and for any other charges due us, including any fees set forth in this Section. If payment is not received 10 days after the due date, this may result in a possible interruption in service and a Late Payment Fee may be assessed. TELL THE BOSS may require you to pay all past due charges, a Reconnect Fee, and all outstanding balances accrued through the date of deactivation, before we reconnect your Services.</li>
		<li>In the event Customer fails to pay their monthly service fee, TELL THE BOSS may, at its election, discontinue, terminate or suspend the Services and delete all Customer Data from its systems, in each case, without incurring any liability to Customer.</li>
		<li>If there are billing errors or other requests for credit, you can contact our Customer Service Center by telephone or in writing. You must contact us within sixty (60) days of the time you receive the billing statement for which you are seeking corrections. Failure to timely notify us of a dispute shall constitute acceptance of the bill. Undisputed portions of the billing statement must be paid before the next billing statement is issued to avoid a disruption in sercvice.</li>
	</ol>
	
	<h3>III. TERMINATION</h3>
	<ol class="primary">
		<li>Termination for Cause. Either party may terminate the Agreement with thirty (30) days notice if the other party has materially breached or is otherwise not in compliance with any provision of the Agreement, and such breach or noncompliance is not cured within such 30 day period. TELL THE BOSS reserves the right to immediately suspend Customer's services without notice, until such breach or noncompliance is cured.</li>
		<li>Termination for Illegal or Other Activity. Notwithstanding the foregoing, TELL THE BOSS may, but has no duty to, immediately terminate Customer from TELL THE BOSS's service without notice if TELL THE BOSS or its service providers, in their sole discretion, conclude that Customer is engaged in illegal activities, or engaged in activities that may damage the rights of TELL THE BOSS or others. Any termination under this Section shall take effect immediately, and Customer expressly agrees that it waives its right to the cure period described herein above.</li>
		<li>Waiver. Customer expressly waives any statutory or other legal protection in conflict with the provisions of this section, to the fullest extent permitted by law. </li>
		<li>Deletion of Information. Upon termination, TELL THE BOSS reserves the right to delete from its servers any and all information contained in Customer's account, including Customer's proprietary information, reference materials, and information about Customer's organization (e.g., its members, user IDs, and passwords).</li>
		<li>Survival. This provision expressly confirms that sections herein pertaining to Proprietary Rights, Indemnification, Disclaimer of Warranties and Liabilities, And Dispute Resolution and Arbitration of this agreement shall survive any termination of the Agreement.</li>
		<li>TELL THE BOSS might in some business requirements, collect certain network information about its Customers Wi-Fi Network in order to provide the Services using TELL THE BOSS (the "Network Information") such as SSID, BSSID, IP Address, Security Protocol etc. TELL THE BOSS may use this information in providing Customer Support and for tracking purposes.</li>
		<li>TRANSFER OF ACCOUNT, SERVICES. TELL THE BOSS may sell, assign or transfer your account to a third party without notice to you. You may not assign or transfer your Services without our written consent, or if your account has an outstanding balance. </li>
	</ol>
	
	<h3>IV. THIRD PARTY CONTENT, LINKS, INTEGRATION AND SERVICES</h3>
	<ol class="primary">
		<li>You acknowledge and agree that the third party content is the copyrighted material of the third party that supplies it, is protected by U.S. copyright law and other applicable laws, and may not be reproduced, used to prepare derivative works, distributed, performed publicly or displayed publicly without the written permission of the third party that supplied it, except to the extent allowed under the U.S. copyright laws, or comparable foreign laws. </li>
		<li>External links may be provided for your convenience, but they are beyond the control of the Website Owner and no representation is made as to their content. Use or reliance on any external links and the content thereon provided is at your own risk. When visiting external links you must refer to that external websites terms and conditions of use. No hypertext links shall be created from any website controlled by you or otherwise to this website without the express prior written permission of the Website Owner. Please contact us if you would like to link to this website or would like to request a link to your website.</li>
		<li>In no event shall any reference to any third party or third party product or service be construed as an approval or endorsement by TELL THE BOSS of that third party or of any product or service provided by a third party. </li>
		<li>All items containing the texting short codes and customer feedback codes displayed in the Customer places of business (the "TELL THE BOSS Advertising Materials") must display somewhere in the content the words "Powered by telltheboss.com," followed by the Service Mark symbol "SM" in at least 6 point font unless other arrangements have been agreed to in writing by both parties.</li>
	</ol>
	
	<h3>V. CUSTOMER INFORMATION AND DISCLOSURE</h3>
	<ol class="primary">
		<li>TELL THE BOSS collects certain personal and business-related information about its Customers in order to provide the Services (the "Customer Information"). If you have provided your contact information, TELL THE BOSS may contact you for marketing purposes by various means, including but not limited to regular mail, email or telephone. When you activate a TELL THE BOSS account, you give your express consent to receive marketing communications via direct mail, email, telephone, pre-recorded messages, text messages, instant messages or other methods.</li>
		<li>In addition to the uses of Customer Information set forth in this section, Customer agrees that TELL THE BOSS may use the Customer Information in connection with its provision of The Services. If Customer purchased the Services as a result of the marketing efforts of a TELL THE BOSS marketing partner, Customer agrees that TELL THE BOSS may disclose the Customer Information to such marketing partner. Notwithstanding the foregoing, TELL THE BOSS will not provide any Customer Information to any third party without Customer's authorization and will use reasonable efforts to prohibit any third party that receives any such Customer Information from selling or redistributing such Customer Information without Customer's authorization.</li>
	</ol>
	
	<h3>VI. EMAIL AND PASSWORDS</h3>
	<ol class="primary">
		<li>DELIVERY. You acknowledge that from time to time, delivery of email messages sent using the Services may be blocked or prevented at destination email servers. Your payment obligation set forth herein continues regardless of whether delivery of such email messages is prevented or blocked by a third party. In consideration for the Professional Services to be provided by TELL THE BOSS, if any, You agree to pay the fees negotiated. </li>
		<li>PASSWORDS. In connection with TELL THE BOSS's provision to Customer of the Services, TELL THE BOSS will send to your designated email address of record in your account information, information such as User Name and/or Passwords which will enable you to access the Software (the "Passwords"). You agree to maintain the Passwords in strict confidence and not to provide the Passwords to any third party. You will notify promptly TELL THE BOSS upon the loss or compromise of any Passwords and you will be solely responsible for all actions and fees incurred as a result of such use of the Passwords. Any unauthorized use of the Passwords by You will constitute a material breach of this Agreement.</li>
		</li>
	</ol>
	<h3>VII. PROHIBITED CONTENT AND COMMERCE.</h3> 
<ol class="primary">
		<li>TELL THE BOSS prohibits the use of TELL THE BOSS's Products and Services by any company or site that engages in any of the following:</li>
			<ol class="secondary">
				<li>Provides, sells or offers to sell any illegal products or services. </li>
				<li>Displays material that exploits children under 18 years of age.</li>
				<li>Posts or discloses any personally identifying information or private information about children without their parents consent.</li>
				<li>Provides material that is grossly offensive, including expressions of bigotry, prejudice, racism, hatred or excessive profanity or post any obscene, lewd, lascivious, filthy, excessively violent, harassing or otherwise objectionable content.</li>
				<li>Engages in any libelous, defamatory, scandalous, threatening, harassing activity.</li>
				<li>Posts any content that advocates, promotes or otherwise encourages violence against any governments, organizations, groups or individuals or which provides instruction, information or assistance in causing or carrying out such violence. In addition, TELL THE BOSS reserves the right to prohibit the use of TELL THE BOSS by any company or site at its sole discretion.</li>
			</ol>
		</li>
	</ol>
	
	<h3>VIII. MISCELLANEOUS</h3>
	<ol class="primary">
		<li>Physical Address/Change of Address. When setting up your TELL THE BOSS account, you agree to provide us with your physical address. You agree to give us prompt notice of your change of name, mailing address, physical address where the device is located or telephone number. You may do this by notifying our Customer Service Center by telephone or in writing.</li>
		<li>Notice. If we send you notice, it will be considered given when deposited in the U.S. Mail, addressed to you at your billing address or hand-delivered to you. Our notice to you will also be effective if provided on your billing statement or by telephone. If you give notice to us, it will be deemed given when received by us at the address listed on the last page of the Privacy Policy. Customer is responsible for notifying TELL THE BOSS of any changes to its e-mail address.</li>
		<li>Applicable Law. This Agreement, including all matters relating to its validity, construction, performance and enforcement, shall be governed by applicable federal law, the rules and regulations of the Federal Communications Commission, and the laws and regulations of the state and local area where Service is provided. These terms and conditions are subject to amendment, modification or termination if required by such regulations or laws. If any provision in this Agreement is declared to be illegal or in conflict with any law or regulation, that provision may be deleted or modified, without affecting the validity of the other provisions.</li>
		<li>Other. This document contains the entire agreement between TELL THE BOSS and you, the customer, and no salesperson, installer, customer service representative, authorized retailer, or other similarly situated individual is authorized to change the terms set forth herein. TELL THE BOSS may, however, change the terms and conditions of this Agreement in the future and will notify you if that occurs. The terms of this Agreement, which either are expressly stated to survive or by their nature would logically be expected to survive termination, shall continue thereafter until fully performed.</li>
	</ol>
	
	<h3>IX. INDEMNITY</h3>
	<p class="important">YOU AGREE TO DEFEND, INDEMNIFY AND HOLD HARMLESS TELL THE BOSS FROM AND AGAINST ANY AND ALL CLAIMS, PROCEEDINGS, INJURIES, LIABILITIES, LOSSES, COSTS AND EXPENSES (INCLUDING REASONABLE ATTORNEYS' FEES), INCLUDING, BUT NOT LIMITED TO, CLAIMS ALLEGING NEGLIGENCE OR INFRINGEMENT AGAINST TELL THE BOSS OR ITS SERVICE, RELATING TO OR ARISING OUT OF YOUR BREACH OF ANY TERM OF THIS AGREEMENT, OR YOUR MISUSE OF THE TELL THE BOSS SERVICE.</p>
	
	<br><h3>X. WARRANTY DISCLAIMER</h3>
	<p class="important">YOU UNDERSTAND AND AGREE THAT THE TELL THE BOSS SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TELL THE BOSS MAKES NO WARRANTY THAT THE ITS SERVICES WILL MEET YOUR REQUIREMENTS, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; NOR DOES TELL THE BOSS MAKE ANY WARRANTY AS TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE SERVICES (INCLUDING THIRD PARTY CONTENT), THAT ANY DEFECTS IN THE SERVICES WILL BE CORRECTED OR THAT THE SERVICES WILL BE COMPATIBLE WITH ANY OTHER SPECIFIC HARDWARE OR SERVICE. FURTHER, TELL THE BOSS DOES NOT WARRANT THAT THE SERVICES OR THE TELL THE BOSS SERVERS THAT PROVIDE YOU WITH DATA AND CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU (AND NOT TELL THE BOSS) ASSUME THE ENTIRE COST OF ALL NECESSARY MAINTENANCE, REPAIR OR CORRECTION. TELL THE BOSS ALSO ASSUMES NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR ANY DAMAGES TO, OR VIRUSES THAT MAY INFECT YOUR TELL THE BOSS WIZIT DEVICE, SOFTWARE, OR OTHER HARDWARE. TELL THE BOSS AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, REGARDING THE SERVICES, TELL THE BOSS WIZIT DEVICE, OR SOFTWARE, INCLUDING ANY IMPLIED WARRANTY OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON- INFRINGEMENT OF THIRD PARTY RIGHTS.</p>
	
	<br><h3>XI. LIMITATION OF TELL THE BOSS'S LIABILITY</h3>
	<p class="important">IN NO EVENT WILL TELL THE BOSS OR ITS SUPPLIERS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, USE OF CUSTOMER INFORMATION, LOSS OF DATA, BUSINESS INTERRUPTION, OR OTHER INDIRECT, CONSEQUENTIAL, SPECIAL, OR INCIDENTAL DAMAGES OF ANY NATURE ARISING FROM OR RELATING TO YOUR USE OF THE TELL THE BOSS SERVICES, TELL THE BOSS WIZIT DEVICE, OR USE OF THE SERVICES THROUGH YOUR ACCOUNT BY ANYONE ELSE, EVEN IF TELL THE BOSS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO CASE WILL TELL THE BOSS'S TOTAL CUMULATIVE LIABILITY TO YOU AND ANYONE WHO USES THE WIZIT SERVICE THROUGH YOUR ACCOUNT, FOR ANY AND ALL CLAIMS UNDER ANY THEORY OF LAW, EXCEED THE AGGREGATE AMOUNT YOU PAID TO TELL THE BOSS IN THE PRECEDING TWELVE MONTHS. YOU UNDERSTAND THAT THESE LIMITATIONS OF TELL THE BOSS'S AND TELL THE BOSS'S SUPPLIERS' LIABILITY ARE A FUNDAMENTAL PART OF THIS AGREEMENT.</p>
	<p>Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Additionally, this provision is not intended to limit TELL THE BOSS's liability in the event of TELL THE BOSS's willful or intentional misconduct</p>
	
	<br><h3>XII. FORCE MAJEURE</h3>
	<p>TELL THE BOSS will not be liable or deemed to be in default for any delay or failure in performance under the Agreement resulting directly or indirectly from acts of nature or causes beyond its reasonable control, including acts of war, acts of God, earthquake, flood, embargo, riot, sabotage, labor shortage or dispute, governmental act, failure of the Internet, or failure by other suppliers, service providers or carriers.</p>
	
	<br><h3>XIII. ENTIRE AGREEMENT</h3> 
	<p>This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all previous proposals, both oral and written.</p>
	
	<br><h3>XIV. DISPUTE RESOLUTION AND ARBITRATION</h3>
	<ol class="primary">
		<li>Attempt to Resolve. All disputes concerning the Agreement and/or Services shall be resolved by the following process:
			<ol class="secondary">
				<li>Customer must first document any claim or dispute to TELL THE BOSS in writing by contacting <a href="mailto:info@TelltheBoss.com">info@TelltheBoss.com</a>.</li>
				<li>If Customer's claim or dispute cannot be resolved within sixty (60) calendar days, and Customer elects to continue dispute, Customer must request arbitration as provided below.</li>
			</ol>
		</li>
		<li>Arbitration. Except as expressly provided below, any controversy or claim arising out of or relating to this Agreement or the breach thereof, shall be settled by final and binding arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules. Judgment on the award rendered by the arbitrator may be entered in a court of competent jurisdiction. Arbitration will be conducted by a single arbitrator.</li>
		<li>Waiver of right to trial. Customer understands and acknowledges that it is waiving the right to have any dispute heard by a jury and determined in a court of law.</li>
		<li>No Punitive Damages. The parties agree that this Agreement evidences a transaction in interstate commerce and this arbitration provision will be interpreted and enforced in accordance with the Federal Arbitration Act and federal arbitration law. The parties agree that they will not seek, and an arbitrator may not award, relief in excess of or contrary to what this Agreement expressly provides, and an arbitrator may not award punitive damages. The parties further agree that an arbitrator may not order consolidation or class arbitration. Each party will bear the costs of arbitration equally but each is responsible for its own attorney fees in arbitration and legal proceedings.</li>
		<li>Arbitration Confidentiality. Any arbitration shall be confidential, and neither Customer nor TELL THE BOSS may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award. Judgment on any arbitration award may be entered in any court having proper jurisdiction. If any portion of this arbitration clause is determined by a court to be inapplicable or invalid, the remainder shall still be give force and effect. </li>
		<li>Waiver of Punitive Damage Claims and Class Actions. By this Agreement, both Customer and TELL THE BOSS are waiving certain rights to litigate a dispute in court. If for any reason this arbitration clause is deemed inapplicable or invalid, Customer and TELL THE BOSS both waive, to the fullest extent allowed by law, any claims to recover punitive or exemplary damages and any right to pursue any claims on a class or consolidated basis or in a representative capacity.</li>
		<li>Governing Law. For any matter not subject to arbitration, Customer and TELL THE BOSS agree to submit to the personal and exclusive jurisdiction of U.S. District Court, or in alternatively, other civil court with jurisdiction in Orange County, California. The laws of the State of California shall govern this Agreement, without regard to its conflict of law provisions.</li>
		<li>Not a waiver. TELL THE BOSS's failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the arbitrator or the court should endeavor to give effect to the parties' intentions as reflected in the provision, and agree that the other provisions of the Agreement remain in full force and effect.</li>
		<li>Sunset Provision. Customer agrees that, regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to the use of the Service or the Agreement must be filed within one (1) year after such claim or cause of action arose, or be forever barred. Severability. In the event any provision of this Agreement is held by a tribunal of competent jurisdiction to be contrary to the law, the remaining provisions of this Agreement will remain in full force and effect.</li>
	</ol>
</div>