<div id="main" class="terms">
	<p class="submenu"><a id="sm1" href="<?php echo site_url('mobile_terms_conditions'); ?>">Mobile Terms &amp; Conditions</a>  <a id="sm2" style="left:-10px;" href="<?php echo site_url('business_terms_conditions'); ?>">Business Terms &amp; Conditions</a>  <a id="sm3" style="left:-20px;" href="<?php echo site_url('privacy_policy'); ?>">Privacy Policy</a>  <a id="sm4" class="active" style="left:-30px;" href="<?php echo site_url('sweepstakes_rules'); ?>">Contest Rules</a></p>
	
	<h1>Tell the Boss Contest</h1>
	
	<p style="text-align:center;">This promotion is intended for the participation in the 50 United States and the District of Columbia only and shall be construed and evaluated according to the laws of the United States. Entrants must not enter this contest unless they are a legal resident of the 50 United States or the District of Columbia and 18 years of age or older. Entrants are not eligible if they are an employee of Tell the Boss, Inc., or any of the Participating Clients or subsidiaries.</p><br/>
	
	<h2 style="text-align:center;">The Tell the Boss Customer Feedback Contest - OFFICIAL RULES</h2>
	
	<ol class="primary">
		<li><strong>TO ENTER</strong>: NO PURCHASE NECESSARY TO ENTER OR WIN. Use of clients' services will not increase your chances of winning.<br/>
			Enter the Tell the Boss Customer Feedback Contest (the "Contest"), sponsored by Tell the Boss. ("Tell the Boss" or “Tell the Boss, Inc.”), together with the Tell the Boss participating clients ("Participating Clients"), by:<br/>
			<ol class="secondary">
				<li>Scanning the QR symbol on the placard, receipt, sign or other media ("Media") posted at the place of business (“QR Scanning Entry”); or</li>
				<li>Texting the Code using a cell phone to 22121. Text message and data charges rates may apply (“Texting Entry”); or</li>
				<li>Logging in to <a href="<?php echo site_url('welcome'); ?>">http://www.telltheboss.com/</a> and then entering the code ("Code") for the place of business that is shown on the media to register your feedback (“Login Entry”).</li>
			</ol>
		</li>
		<li>By submitting an entry via one of the three methods described above, you will automatically be entered into the Contest. Your opinion of your experience with the service of our Participating Client will be used by the Participating Client to improve the quality of their service. Your entry will be subject to these Official Rules. Each texted reply, QR reply or login reply will serve as one (1) entry in the Contest. If the Entrant selects the option of entering an additional survey (if provided), as introduced to the Entrant at the end of the exchange with the Tell the Boss service, and complete the survey, the Entrant will be given an additional one (1) entry in the Contest</li>
		<li>Each Contest Period a winner will be chosen to win a prize as advertised on the Media. The prize will vary in value from one Participating Client to the next, and the number of entries made on behalf of that Participant Client will determined the odds of winning the prize.</li>
		<li>To enter by mail (Mail Entry), with no purchase necessary and without completing a survey, please hand-write the following sentence "Please enter me in the Tell the Boss Sweepstakes for a chance to win one (1) prize" on a sheet of paper on which you have hand-printed your first name, last name, home telephone number, full address (no PO Boxes accepted), email address, and the name of a participating client and mail it in a separate envelope with sufficient postage to: Tell the Boss, Inc., 27762 Antonio Parkway, Suite L-1504, Ladera Ranch, CA 92694. Each entry must be sent separately, and multiple entries sent in a single envelope will be eliminated from entry into the Sweepstakes.</li>
		<li>Limit one (1) QR Scanning Entry, Texting Entry or Login Entry every day. Entries received in violation of the foregoing limitation shall be null, void and of no force or effect. All entries via QR Scanning Entry, Login Entry or Texting Entry methods must offer opinions of quality of service and/or quality of product, as prompted by the media involved.<br/>
		<strong>EACH ENTRANT HEREBY EXPRESSLY AUTHORIZES AND CONSENTS TO TELL THE BOSS CONTACTING THE ENTRANT, ONLY IN RELATION TO THE CONTEST, VIA THE ENTRANT'S METHOD OF CONTACT INTO THE CONTEST OR ANY OTHER CONTACT METHOD AUTHORIZED BY THE ENTRANT</strong>.<br/>
		In the event of a dispute regarding the identity of the person submitting the entry, in the case of a QR Scanning Entry, Login Entry or Texting Entry, the entry will be deemed submitted by the person in whose name the telephone or Internet account is registered. For any method used to enter the Contest, an "Entrant" shall mean an individual who has successfully submitted a valid, complete and legitimate Contest entry, in strict accordance with these Official Rules, as interpreted solely by Tell the Boss, Inc.</li>
		<li><strong>CONTEST PERIOD</strong>: The period of the Contest will change from time to time, and from one Participating Client to the next. That period will be displayed on the Media and may be daily, weekly, monthly or quarterly (“Contest Period”). The Contest consists of individual Contest selections. Each Contest is separate from any other Contest . Each Contest entry period begins on the first day of the Contest Period at 12:00 am pacific standard time ("Entry Commencement Date") and ends on the last day of the Contest Period at 11:59 pm pacific standard time ("Entry End Date"). All eligible entries must be received by the end of the Contest Period Entry End Date. ALL ENTRIES RECEIVED AFTER THE ENTRY END DATE WILL BE INVALID, DISQUALIFIED FROM THE CONTEST, AND NULL AND VOID.</li>
		<li><strong>ELIGIBILITY</strong>: The Contest is open only to legal residents of the 50 United States and the District of Columbia, and who are 18 years of age or older. The Entrant is not eligible if, during the Contest period they are (or live with) or an immediate family member of (parent, child, sibling and spouse of any those) an employee, representative, or agent of Tell the Boss or Participating Clients or any of its subsidiaries, licensees or affiliates.</li>
		<li><strong>WINNER SELECTION</strong>: Tell the Boss or the Participating Client will make the winner selection based on the quality of the comment made through the Tell the Boss service. The evaluation of the comment will be based on the comment's helpfulness in improving the service of the business where the comment is solicited.</li>
		<li><strong>PRIZES</strong>: Each Contest winner will receive a prize as described in the Media. Each prize will be awarded, provided such prize is properly claimed. If the winner does not claim or qualify to receive the prize, the first alternate winner will be notified and provided the opportunity to claim the prize. In the event the Entrant does not wish to be considered for eligibility of the prize, or wishes to be exempt from the terms and conditions set herein, the Entrant may decline the prize at the time of contact. Because the Entrant is bound by these official rules, no additional contact to the Entrant regarding the Contest will be made by Tell the Boss thereafter.</li>
		<li><strong>WINNER NOTIFICATION</strong>: Each Contest winner entering the Contest via the QR Scanning Entry, Login Entry or Texting Entry will be notified by telephone, email, text message or postal mail. Each Contest winner may be required to return a signed declaration and release of liability within twenty (20) days of notification. If Tell the Boss is unable to contact a winner despite Tell the Boss's reasonable efforts to do so, the next Entrant will be selected.<br/><br/>
		FAILURE TO RETURN THE SIGNED DECLARATION AND RELEASE OF LIABILITY, IF APPLICABLE, WITHIN TWENTY (20) DAYS OF NOTIFICATION MAY RESULT IN FORFEITURE OF PRIZE AND THE SELECTION OF AN ALTERNATE WINNER, WITHOUT FURTHER NOTICE FROM TELL THE BOSS, INC. IF THE RETURN OF ANY PRIZE NOTIFICATION OR THE PRIZE ITSELF IS FOUND TO BE UNDELIVERABLE, THE PRIZE WILL BE FORFEITTED BY THE ENTRANT AND DELIVERED TO THE NEXT SELECTED ENTRANT IN THE SAME MANNER.</li>
		<li><strong>GENERAL CONDITIONS</strong>: This Contest is void outside of the United States and the District of Columbia and wherever prohibited by law. All federal, state, and local laws and regulations apply to this Contest. No prize transfers, cash redemption or substitutions permitted except in the event of unavailability of prize, in which case Tell the Boss may, in its own discretion, substitute a prize of equal or greater value. Tell the Boss will not replace any lost, misplaced or stolen prizes. Federal law may require that a Form 1099 be supplied to the winner. All federal, state and local taxes on the prize, if any, are the sole responsibility of the winner. The Contest is also subject to these Official Rules. If the Entrant cannot or will not comply with these Official Rules, they should not enter or participate in the Contest. By entering this Contest, Entrants agree to abide by and be bound by these Official Rules and to waive any right to claim any ambiguity or error in these Official Rules or the Contest itself. Entrants agree to be bound by all decisions of Tell the Boss, whose decisions are final and binding. Submission of entry constitutes permission for Tell the Boss to use the Contest winner's name, city and state of residence, except where prohibited by law.</li>
		<li><strong>PRIVACY POLICY</strong>: Any information collected from Entrants registering or entering the Contest shall be stored, maintained, collected, used and/or disclosed only in the manner consistent with these Official Rules and the Tell the Boss privacy policy, which can be found at <a href="<?php echo site_url('welcome'); ?>">http://www.telltheboss.com/</a>. Any opinions or survey responses regarding the Participating Clients will be used to evaluate and improve the Participating Client’s businesses and for any other permitted purposes.</li>
		<li><strong>DISCLAIMERS</strong>: BY ENTERING THE CONTEST, EACH ENTRANT RELEASES FOREVER TELL THE BOSS, INC. AND ALL PARTICIPATING CLIENTS FROM, AND WAIVES ANY CLAIM IT MAY HAVE AGAINST TELL THE BOSS, INC. AND ALL PARTICIPATING CLIENTS FOR, ANY AND ALL RESPONSIBILITY OR LIABILITY FOR ANY AND ALL LOSSES, DAMAGES, LIABILITIES, ACTIONS, INJURIES AND/OR COSTS AND/OR EXPENSES, INCLUDING WITHOUT LIMITATION COURT COSTS AND ATTORNEYS' FEES CONNECTED TO PARTICIPATION IN THE CONTEST, DIRECTLY OR INDIRECTLY, INCLUDING ENTRY, CONTACT METHODS, OR ACTIVITIES RELATED TO DELIVERY OF THE PRIZE OR ANY SUBSEQUENT USE OF THE PRIZE AWARDED HEREIN. <br/><br/>
		Each Entrant agrees that Tell the Boss, Inc. or Participating Clients will not be responsible or liable for any entries which are not in compliance with these Official Rules, or for any late, garbled, lost, illegible, stolen, damaged, incomplete, or misdirected entries or data transmission. Tell the Boss, Inc. and Participating Clients are not responsible for technical, software, hardware or communication malfunctions of any kind, or failed, incomplete, incorrect, inaccurate, garbled, or delayed electronic communications caused by the user or by any of the computer programming or telephone equipment associated with this Contest, by any human error or by the failure of any mail or delivery service which may occur in the processing of the entries in this Contest. Tell the Boss, Inc. reserves the right, at its sole discretion, to terminate, suspend or modify the Contest if the Contest is not capable of running as planned, due to technical difficulties related to, but not limited to, infection by computer virus, tampering, fraud, technical failures, or any other problems beyond the control of Tell the Boss. Tell the Boss reserves the right, at its sole discretion, to disqualify any individual it determines to be violating the Official Rules, or acting in a manner that compromises the Contest rules or operating methods, or disrupts the business processes of Tell the Boss. For the purposes of Tell the Boss, Inc., entering the Contest via QR Scanning Entry, Login Entry or Texting Entry methods the Entrant is not subscribing for anything other than the initial message which provides a method to submit their feedback and/or a link to the survey, and entry into the Contest, set forth in these Official Rules. The Participating Client reserves the right to add the Entrant to their company’s mailing list for special coupons and deals, as well as to contact the Entrant by phone or email regarding the content of the comment for business improvement purposes. However, such Participating Clients will provide a means to unsubscribe or to be removed from such lists in accordance with their own privacy policies. When using the Texting Entry method, should the Entrant attempt to unsubscribe by texting “STOP”, the Entrant’s consent to receive text messages from Tell the Boss shall extend to a message confirming that they have unsubscribed from the Tell the Boss service.</li>
		<li><strong>CANCELLATION, TERMINATION OR SUSPENSION; DAMAGES</strong>: In the event the Contest is canceled, terminated, modified or suspended, notification will be posted by Tell the Boss, Inc. at <a href="<?php echo site_url('welcome'); ?>">http://www.telltheboss.com/</a> Any attempt by an Entrant or other individual to deliberately damage the website <a href="<?php echo site_url('welcome'); ?>">http://www.telltheboss.com/</a> or undermine the operation of the Contest is a violation of criminal and civil laws and should such an attempt be made, Tell the Boss, Inc. reserves the right to seek any and all damages and other remedies from any such person(s) to the fullest extent permitted by law.</li>
	</ol>
		
	<p><strong>©2013 by TELL THE BOSS, INC., All Rights Reserved.</strong></p>
	
</div>